-- PostgreSQL table for contact inquiries.
-- Important: phone must NOT be unique (the same person can inquire multiple times).
CREATE TABLE IF NOT EXISTS customer (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone VARCHAR(50) NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  inquiry_method VARCHAR(10) NOT NULL DEFAULT 'email',
  inquiry_status VARCHAR(20) NOT NULL DEFAULT '未対応',
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_customer_created_at ON customer (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_customer_phone ON customer (phone);

-- Migration for older schema versions where `phone` was the PRIMARY KEY.
DO $$
BEGIN
  IF to_regclass('public.customer') IS NOT NULL
     AND NOT EXISTS (
       SELECT 1
       FROM information_schema.columns
       WHERE table_schema = 'public'
         AND table_name = 'customer'
         AND column_name = 'id'
     ) THEN
    ALTER TABLE customer ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
    UPDATE customer SET id = DEFAULT WHERE id IS NULL;
    ALTER TABLE customer ALTER COLUMN id SET NOT NULL;
    ALTER TABLE customer DROP CONSTRAINT IF EXISTS customer_pkey;
    ALTER TABLE customer ADD CONSTRAINT customer_pkey PRIMARY KEY (id);
  END IF;
END $$;
